import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Footer} from 'src/components/Footer'
import { Scene } from 'src/components/Scene'


export default function Home() {
  
  return (
    
    <div className={styles.container}>
      
      <Head>
        <title>AI-Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Scene/>
      
      

      {/* <Footer />  */}

      
    </div>
  )
}
